CREATE DATABASE n8;

USE n8;

CREATE TABLE DEPARTAMENTO(
IdDepartamento INT IDENTITY PRIMARY KEY,
NomeDepartamento VARCHAR (50)
);

CREATE TABLE PROJETO(
IdProjeto INT IDENTITY PRIMARY KEY,
NomeProjeto VARCHAR (50)
);

CREATE TABLE LOCALIZACAO(
IdLocal INT IDENTITY PRIMARY KEY,
Rua VARCHAR (100),
IdDepartamento INT FOREIGN KEY REFERENCES DEPARTAMENTO (IdDepartamento)
);

CREATE TABLE EMPREGADO(
IdEmpregado INT IDENTITY PRIMARY KEY,
Nome VARCHAR (100),
IdLocal INT FOREIGN KEY REFERENCES LOCALIZACAO (IdLocal)
);

CREATE TABLE DEPENDENTE (
IdDependente INT IDENTITY PRIMARY KEY,
Nome VARCHAR (100),
IdEmpregado INT FOREIGN KEY REFERENCES EMPREGADO (IdEmpregado)
);

CREATE TABLE MEMBROS(
IdMembro INT IDENTITY PRIMARY KEY,
IdEmpregado INT FOREIGN KEY REFERENCES EMPREGADO (IdEmpregado),
IdProjeto INT FOREIGN KEY REFERENCES PROJETO (IdProjeto)
);